version: '3'
services:
  server:
    build: ./server
    container_name: nest-app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - '3001:3000'
    depends_on:
      - db

  client:
    build: ./client
    container_name: next-app
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=http://localhost:3001

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
