version: '3'
services:
  server:
    build: ./server
    container_name: nest-app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      - db

  client:
    build: ./client
    container_name: next-app
    ports:
      - '${FRONTEND_PORT}:3000'
    environment:
      - BACKEND_URL=${BACKEND_URL}:${BACKEND_PORT}

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '${DB_PORT}:5432'
